info:
  contact: {}
paths:
  /user/:
    get:
      consumes:
      - application/json
      description: get list of users
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Shows list of User for expenses
      tags:
      - accounts
swagger: "2.0"
